spring:
  application:
    name: chillin
  ai:
    openai:
      api-key: ${API_KEY}
      chat:
        enabled: false
      embedding:
        enabled: false
      image:
        enabled: true
        api-key: ${API_KEY}
        options:
          size: ${IMAGE_SIZE}
  datasource:
    driver-class-name: ${DB_DRIVER_CLASS_NAME:org.h2.Driver}
    url: ${DB_URL:jdbc:h2:mem:testdb}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:}
  servlet:
    multipart:
      max-file-size: ${MAX_FILE_SIZE:10MB}
logging:
  level:
    web: debug
custom:
  image:
    instruction:
      prefix: ${IMAGE_INSTRUCTION_PREFIX:""}
      postfix: ${IMAGE_INSTRUCTION_POSTFIX:""}
  aws:
    accessKey: ${AWS_ACCESS_KEY}
    secretAccessKey: ${AWS_SECRET_ACCESS_KEY}
    bucket:
      name: ${AWS_BUCKET_NAME}
    durationMinutes: ${AWS_DURATION_MINUTES}
  epson-connect:
    printer-address: ${EPSON_PRINTER_ADDRESS}
    client-id: ${EPSON_CLIENT_ID}
    client-secret: ${EPSON_CLIENT_SECRET}
  motion:
      url: ${MOTION_URL}